# This is a basic workflow

name: actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Pre-commit"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: pre-commit
        uses: pre-commit/action@v3.0.0

  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_UPDATE: "True"
          PULL_REQUEST_BRANCH: "deploy"
          PULL_REQUEST_TITLE: "This is an AUTO PR; generated because you're lazy"
          PULL_REQUEST_BODY: "The Justice league has raised this PR on your behalf"
          PULL_REQUEST_ASSIGNEE: "theendless22"
          PULL_REQUEST_LABEL: "Review me!"

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: auto-pull-request
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: shruthinaidu/supe-story-repo
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
